k8sServiceHost: test-control-plane
k8sServicePort: 6443
kubeProxyReplacement: true
externalIPs:
  enabled: true
hostPort:
  enabled: true
image:
  pullPolicy: IfNotPresent
ipam:
  mode: kubernetes
l2announcements:
  enabled: true 
hubble:
  enabled: true 
  relay:
    enabled: true
  ui:
    enabled: true
